spring:

  application:
    name: "batchDemo"


  datasource:
    url: jdbc:postgresql://localhost:5433/batchRev
    username: postgres
    password: imad
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
